### ISSUE TITLE
The repo clones awkwardly on case-insensitive filesystems

### ISSUE THREAD

**Issue by copumpkin** [basvandijk/case-insensitive#17]
This is somewhat ironic (was it intentional??) but if I clone this on a case-insensitive filesystem, the `Data` and `data` folders overlap. This is usually not the end of the world, but it breaks hashing when we use this package in `nix` and similar hash-centric systems. Can the folder structure be rearranged a bit?

/cc @ryantrinkle @jwiegley

**Comment by basvandijk** [comment]
Haha that's indeed ironic!

Fix released as [case-insensitive-1.2.0.4](http://hackage.haskell.org/package/case-insensitive-1.2.0.4).

**Comment by ryantrinkle** [comment]
Thanks!
